jfrog/build-info

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
When execute maven as parallel build, e.g. mvn clean install -T 4. We run into the problem below, 
1) causes pom file not deploy intermittently
* The issue because instance variable Map<String, DeployDetails> deployableArtifactBuilderMap is not thread safe because it's initialize as deployableArtifactBuilderMap = Maps.newHashMap(); Recommended to initialize as Maps.newConcurrentMap(); which is thread safe.
2) unit test fail with error
````java
[ERROR] NullPointerException
java.lang.NullPointerException
at org.jfrog.build.extractor.maven.BuildInfoRecorder.isTestsFailed(BuildInfoRecorder.java:314)
at org.jfrog.build.extractor.maven.BuildInfoRecorder.mojoSucceeded(BuildInfoRecorder.java:274)
at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapul …
```
> Fix maven parallel build issue

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/BuildInfoBaseTask.java
When doing `./gradlew artifactoryPublish` in our project with the latest version (i.e. `master`), we get
```
Caused by: java.io.IOException: Could not publish build-info: Failed to send build descriptor : HTTP response code: 500. HTTP response message: Internal Server Error
at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.sendBuildInfo(ArtifactoryBuildInfoClient.java:244)
at org.jfrog.gradle.plugin.artifactory.task.BuildInfoBaseTask.prepareAndDeploy(BuildInfoBaseTask.java:377)
at org.jfrog.gradle.plugin.artifactory.task.BuildInfoBaseTask.collectProjectBuildInfo(BuildInfoBaseTask.java:126)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at …
```
> Fix HTTP response 500 on artifactoryPublish.

- build-info-extractor-ivy/src/main/java/org/jfrog/build/extractor/listener/ArtifactoryBuildListener.java
We use ant presetdef tasks to simplify some of our common calls into Ivy's ant tasks. This has the side effect that these ivy calls are wrapped and no longer get detected in Jenkins by the artifactory plugin. This handles the cases in which the IvyTask is wrapped within PreSetDef task.
> Handle ant IvyTasks that may be wrapped by Ant presetdef tasks

- build-info-client/src/main/java/org/jfrog/build/client/DeployDetails.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleDeployDetails.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/PublishArtifactInfo.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/BuildInfoBaseTask.java
- build-info-extractor-ivy/src/main/java/org/jfrog/build/context/BuildContext.java
Currently the build extractors for Ivy and Gradle store the resulting list of artifacts to publish in a HashSet. This causes the artifacts to be published in a random order. This updates that to use a TreeSet and provides comparable implementations for related objects so that the published artifacts occur in a deterministic order. This is really helpful for us to determine when a build is complete. This would solve https://www.jfrog.com/jira/browse/GAP-181 in a more predictable manner than is currently implemented.
> Deterministic publish order for gradle and ivy

- build-info-client/src/main/java/org/jfrog/build/client/ArtifactoryHttpClient.java
In case response from the client is not a JSON file, shows the response in the logs.
> Issue 65 - Add more verbose logs

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
Define the default scope for the artifact dependency in case it's value is null or an empty string.
I've already accept the JFrog CLA (adobe sign)
initial discussion on issue #52 
jira issue [here](https://www.jfrog.com/jira/browse/HAP-909)
> [HAP-909] NPE on gather build info

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
Here is a fix for #115.
In newer gradle versions subproject dependencies are directories.  So we should not calculate checksums from them.
> Fix #115: dependencies can be represented as a dir

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/ArtifactoryPlugin.groovy
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/ArtifactoryPluginBase.groovy
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/BuildInfoBaseTask.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
This was raised because of: https://github.com/JFrogDev/build-info/pull/126
The idea of deploying on the last task of the graph gets a bit complex when parallel build is enabled, as we have to deal with waiting for previous tasks to finish, parent dependencies being skipped, triggering errors.
All these complications gradle can already deal with it if you move the deploying action to a task in the rootProject, and you setup dependencies accordingly. 
By doing this I have also detected an incongruity which I needed to fix in order for this to compile:
If I got the idea right, isPublishBuildInfo() (before this diff, in BuildInfoBaseTask.java), should only check the ArtifactoryClientConfiguration, and not the artifactoryPublish task config, as otherwise, the last task specification can …
> Move deploying action to a separated task

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/ArtifactoryPluginBase.groovy
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ProjectsEvaluatedBuildListener.groovy
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/ArtifactoryTask.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
The plugin does not work properly with ConfigureOnDemand.
The callback projectsEvaluated is actually not a good place to do things like "finalizedBy", because in case of using it with configure-on-demand, it gets called when the configuration is already done.
Look at the following SSCCE to reproduce the problem (which is doing the same as you do).
[testGradle.zip](https://github.com/JFrogDev/build-info/files/1635366/testGradle.zip)
> Making it work with configureOnDemand

- build.gradle
There already is
```
compile gradleApi()
```
That makes the presence of `groovy-all` in the compile classpath
redundant.
Also it causes module version conflicts in newer versions of gradle
since gradle brings in a newer version of groovy.
Fixes #180
> Remove groovy from compile classpath

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java
- gradle/wrapper/gradle-wrapper.properties
The artifacts, dependency and other metadata was previously resolved
when the publication was specified to artifactory.
This can cause missing and/or incomplete pom files being uploaded to
artifactory.
> Fix #138 delay resolving of publication artifacts.

- build.gradle
With newer versions of gradle, that task is already available. This causes errors in building.
Also, the wrapper currently uses 4.8 whereas this task tried to use 2.4
> Remove wrapper task

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java
Pretty straightforward as it effectively [inline the code](https://github.com/gradle/gradle/blob/28d8f6d3372993d2b2212161c85c6ddf797ceb20/subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenNormalizedPublication.java#L73-L76) from the deprecated method in Gradle.
> Replace deprecated method use

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientConfigurationFields.java
While helping customers and OSS projects to optimize the performance of their build, we (Gradle, Inc.) noticed that the `artifactoryDeploy` task was very long to execute.
This is because uploads are executing serially.
This PR allows to upload artifacts in parallel.
The number of forked threads defaults to 8, but can be customized using the `publishForkCount` in the `artifactory{}` DSL extension.
See for instance the net results in the https://github.com/spring-projects/spring-framework OSS project:
- before this PR:
- https://ge.spring.io/s/ju7kyr3p4m62c/timeline?task=jb2ueukhvhszg
- `artifactoryDeploy` needs 1 minute to perform 89 uploads
- with this PR:
- https://ge.spring.io/s/e65kj475jjspk/timeline?task=jb2ueukhvhszg
- `artifactoryDeploy` needs 7 seconds to perform 89 uploads
> Allow parallel upload of artifacts

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/ArtifactoryTask.java
- build.gradle
Hi
This pull request fixes the following warnings when using Gradle 6.x:
```
> Task :build-info-extractor-gradle:validatePlugins FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':build-info-extractor-gradle:validatePlugins'.
> Plugin validation failed. See https://docs.gradle.org/6.1-20191004133052+0000/userguide/more_about_tasks.html#sec:task_input_output_annotations for more information on how to annotate task properties.
> Warning: Type 'ArtifactoryTask': field 'mavenPublications' without corresponding getter has been annotated with @Input, @Optional.
> Warning: Type 'ArtifactoryTask': field 'publishConfigs' without corresponding getter has been annotated with @InputFiles, @Optional.
> Warning: Type 'ArtifactoryTask': property …
```
> ArtifactoryTask: Add proper gradle annotations to avoid 6.x warnings

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
Handle this kind of warnings by using Gradle's Mutex mechanism:
> The configuration :services:webservice:annotationProcessor was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.6.3/userguide/troubleshooting_dependency_resolution.html#sub:configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.
Resolves also: https://github.com/jfrog/build-info/issues/255
Guard `configuration.getResolvedConfiguration()` and remove parallelism when populating the build info object.
Uploads still occur in parallel, as contributed in https://github.com/jfrog/build-info/pull/261. …
> Gradle - Remove 'The configuration was resolved without accessing the project in a safe manner' warning

- README.md
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java
This pull request addresses the issue raised in #247 for both Ivy and Maven.
> Publication of all artifacts for Ivy and Maven

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ProjectsEvaluatedBuildListener.groovy
https://github.com/jfrog/build-info/issues/203
> The IvyArtifactRepository.layout(String, Closure) method has been deprecated

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/resolver/ArtifactoryEclipseRepositoryListener.java
Allow plugin without version resolution. Fix this error:
> [main] ERROR org.apache.maven.cli.MavenCli - Error resolving version for plugin 'org.sonarsource.scanner.maven:sonar-maven-plugin' from the repositories [local (/Users/yahavi/.m2/repository), artifactory-release (http://127.0.0.1:8081/artifactory/libs-release)]: Plugin not found in any plugin repository
Caused by previous commit: https://github.com/jfrog/build-info/commit/e6c67cd5ae6819382a99825ef504337d19164841#diff-6b303c85142da9302de6e07eb769c56cR195-R197.
> Building with Install -U Fails Build - Fix

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java
Fix the following exception in Gradle 4:
> Caused by: java.lang.NoSuchMethodError: org.gradle.api.publish.maven.internal.publisher.MavenNormalizedPublication.getAdditionalArtifacts()Ljava/util/Set;
at org.jfrog.gradle.plugin.artifactory.task.helper.TaskHelperPublications.getArtifactDeployDetails(TaskHelperPublications.java:257)
@ljacomet the exception introduced by the following change:  https://github.com/jfrog/build-info/pull/265/commits/04e8afd9ae4550ef2b04d8f89a3e91c0f1bd49b5#diff-dd7b7a4cca93e9ac769933a1811d39dcR255. 
Can you please take a look on this pull request? Thanks!
> Add publishing of metadata (.module file) to the plugin - Gradle 4 fix

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
This supercedes #275 and fixes the issues reported there.  I've tested this with Gradle 4.10.3, 5.6.4, and 6.0 using the example project [here](https://github.com/jfrog/project-examples/blob/master/gradle-examples/gradle-example-publish/build.gradle).
I'm happy to discuss if any of the changes are unclear.
> Reintroduce buildinfo computation parallelism

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java
This fixes #284 and also addresses the Maven publication issue raised in #271
> Fix Ivy + Gradle Module Metadata skipping on Gradle 6+

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/ArtifactoryPlugin.groovy
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/ArtifactoryPluginBase.groovy
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleDeployDetails.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleModuleExtractor.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/ProjectUtils.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/ArtifactoryTask.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/ExtractModuleTask.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ModuleExtractor.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ModuleExtractorUtils.java
This is a followup from #293.  Given the difficulties with incorporating the integration tests I included there, I'm carving off the functional change that I made in that PR so that it can be tested as normal and we can resolve the issues with the integration tests I added as a separate PR.
This refactors the module info extraction to make it safer. With #287 this was parallelized in a fairly unsafe manner using some Gradle internal APIs. This breaks up the module info extraction so that instead of a single task in the root project reaching across and resolving configurations in other projects, each project has its own extraction task that produces a module info artifact by resolving only the configurations in its project. Then the root project has a configuration that aggregates all of …
> Improve module info extraction to gather info safely in parallel (only)

- build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmCommand.java
https://github.com/jfrog/build-info/issues/315
This fix handle relative paths better. Specifically it fix these cases:
**Before the fix:**
|Path|Abs|Working Dir
|:----:|:----:|:------------:|
|.|abs current dir path|null
|package.json|abs current dir path|null
|path to dir|abs path to dir|path to dir
|path to package.json|abs path to package.json|path to dir containing package.json
**After the fix:**
|Path|Abs|Working Dir
|:----:|:----:|:------------:|
|.|abs current dir path|parent of abs path
|package.json|abs current dir path|parent of abs path
|path to dir|abs path to dir|path to dir
|path to package.json|abs path to package.json|path to dir containing package.json
> BI-518 - java.lang.NullPointerException with rtNpm install in Container

- build-info-extractor/src/main/java/org/jfrog/build/extractor/ModuleParallelDeployHelper.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
Following #304 , reducing to 3.
> BI-522 - Reduce default deployment threads for Gradle and Maven

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/ArtifactoryPluginBase.groovy
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/ModuleInfoFileProducer.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
#334 describes a problem whereby when the root project does not produce publishable artifacts, but has the same coordinates as a subproject, the subproject will not be published.  This happens because the inter-project dependencies are wired together via artifacts and when two projects have matching coordinates, they appear as the same module so conflict resolution kicks in and resolves to one project or the other.  If this were two subprojects, there would be no reason to apply the artifactory plugin to both projects (otherwise they would both publish the same module).  But in the case where the root project does not publish any artifacts, it is entirely feasible to apply the plugin to both the root project and the subproject event though the coordinates are the same.
These changes fix …
> Wire module info files without using dependencies

- build-info-api/src/main/java/org/jfrog/build/api/BaseBuildFileBean.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleModuleExtractor.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
> BI-525 - Add artifact's path field to Build-Info in Maven and Gradle

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
This addresses "Gradle Build Info Extractor should not add modules without artifacts" https://github.com/jfrog/build-info/issues/342
> GradleBuildInfoExtractor: only add modules with artifacts to build info

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ProjectsEvaluatedBuildListener.groovy
-----
**The issue**
In CI builds, MavenJava and IvyJava default publications are automatically injected. This behavior causes issue when running, for example, C++ project with Gradle.
**Solution**
Inject MavenJava and IvyJava only if `java` or `java-library` plugin are applied.
**More information**
Jenkins Jira isssue: https://www.jfrog.com/jira/browse/HAP-1307
> Default MavenJava and IvyJava publications added in non Java projects

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ProjectsEvaluatedBuildListener.groovy
- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/GradlePluginTest.java
- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Utils.java
- build-info-extractor-gradle/src/test/resources/integration/buildinfo.properties
- build-info-extractor-gradle/src/test/resources/integration/gradle-example-ci-server/build.gradle
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientConfigurationFields.java
-----
Jenkins PR: https://github.com/jfrog/jenkins-artifactory-plugin/pull/309
Add 'publications' field to the publisher to allow customizing the Gradle publications.
If publications were chose, don't add the default mavenJava and ivyJava publications.
> Allow choosing the Gradle publications during Gradle CI builds

- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/executor/CommandExecutorTest.java
> BI-530 - Fix CommandExecutor environment initialization for Windows machines

- build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/NpmDriver.java
- build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmBuildInfoExtractor.java
- build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmDependencyTree.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/DependenciesTree.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/Scope.java
-----
* Add scope set to the dependencies tree node.
* Remove redundant 'npm ls --only=dev' command during the npm extractor. Instead, run 'npm ls --json --long' to get all required information.
> BI-529 - Add scopes to dependencies tree nodes

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
> NullPointerException in GradleBuildInfoExtractor when module dependencies are null

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/ArtifactoryPluginBase.groovy
-----
Jira - https://www.jfrog.com/jira/browse/GAP-321
To allow incremental builds, extractModuleInfo task should always be executed.
Otherwise, users have to clean between every build.
> Builds are not incremental

- build-info-client/src/main/java/org/jfrog/build/client/Version.java
-----
Actual:
If the Artifactory URL is incorrect, the "Test Connection" button results are "This plugin is compatible with version 2.2.3 of Artifactory and above. Please upgrade your Artifactory server!".
Expected:
"There is either an incompatible or no instance of Artifactory at the provided URL."
> Version test of incorrect Artifactory URL returns wrong message

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryXrayClient.java
-----
The username-password constructor left intact in order to not break the API.
> BI-540 - The Xray client does not support access tokens

- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/types/NugetPackgesConfig.java
-----
This PR fixes https://github.com/jfrog/jenkins-artifactory-plugin/issues/329
> Bug fix - NuGet - package.config read fails

- build-info-api/src/main/java/org/jfrog/build/api/BuildInfoFields.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
- build-info-extractor-gradle/src/test/resources/integration/gradle-example/build.gradle
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBuildInfoClient.java
-----
#341 
Instead of using 10MB, allow configuring the minimal file size of checksum deploy:
```gradle
allProjects {
artifactoryPublish {
clientConfig.publisher.minChecksumDeploySizeKb = 123
}
}
```
> Allow configuring min size of checksum deploy in Gradle

- build-info-api/src/main/java/org/jfrog/build/api/util/CommonUtils.java
- build-info-api/src/test/java/org/jfrog/build/api/util/CreateTempDirTests.java
- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/DockerUtils.java
- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/extractor/DockerPull.java
- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/extractor/DockerPush.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/spec/SpecsHelper.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/packageManager/PackageManagerExtractor.java
> Exception raised during download when 'java.io.tmpdir' is not defined

- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/DotnetDriver.java
- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/NugetDriver.java
- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/ToolchainDriverBase.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
This pull requests adds a log print for each "nuget" and "dotnet" command execited.
-----
> Log the executed "nuget" and "dotnet" commands

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
- build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/extractor/GoExtractorTest.java
- build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/NpmDriver.java
- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/DotnetDriver.java
- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/NugetDriver.java
- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/ToolchainDriverBase.java
- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/extractor/NugetRun.java
- build-info-extractor-pip/src/main/java/org/jfrog/build/extractor/pip/PipDriver.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/issuesCollection/IssuesCollector.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/util/GitUtilsTest.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/executor/CommandExecutorTest.java
-----
This PR is targeting an issue introduced in https://github.com/jfrog/build-info/pull/420.
The command executor in mac is expecting to get all command arguments as a string variable.
For example, when running the go test in the Jenkins Artifactory plugin we may get an error with the usage of Go:
```
[Pipeline] rtGoRun
Executing command: /bin/sh -c go list -m
Go is a tool for managing Go source code.
Usage:
go <command> [arguments]
```
> Log the executed "nuget" and "dotnet" commands - Fix

- build-info-extractor-pip/src/main/java/org/jfrog/build/extractor/pip/extractor/PipBuildInfoExtractor.java
- build-info-extractor-pip/src/test/java/org/jfrog/build/extractor/pip/extractor/PipBuildInfoExtractorTest.java
-----
Resolves #429 
* Reduce AQL bulk size from 100 to 3
* Optimize AQL queries by:
* Change `"name":{"$match":"%s"}` to `"name":"%s"` because the file names are not wildcard patterns, we should use `equal` instead of `match`.
* Delete redundant fields:
* Remove `"path":{"$match":"*"}` because it is already the default
* Remove spaces
> Optimize pip

- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
> Increase command executor timeout to 30 seconds

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/GitUtils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/UrlUtils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/util/UrlUtilsTest.java
-----
When the VCS URL contains a URL with credentials, instead of masking it with '***', remove the credentials. This way, the VCS URL will be clickable.
For example:
Before the change:
`https://***:***@github.com/jfrog/build-info`
After the change:
`https://github.com/jfrog/build-info`
> BI-552 - Improve VCS URL algorithm

- Jenkinsfile
-----
Add support for `ALL` option when running the build info Jenkins job.
When the project is auto-triggered by SCM, the multi-select will choose the first option. In order to automatically build all projects, we should have the first option to be 'ALL'.
> Build automation - build all if none selected - fix

- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/types/DockerImage.java
> Improve collect  build info logging for docker push/pull

- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/types/DockerImage.java
> BI-556 - Improve collect build info logging for docker push/pull - Improvement

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ProjectsEvaluatedBuildListener.groovy
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java
-----
Following the discussion in #407, the _publications_ method now accepts a new parameter, "ALL_PUBLICATIONS", that will trigger the usage of all publications configured in the build script.
The parameter can currently be passed in a `build.gradle` file and used by the Artifactory Plugin directly, or be passed to the _publications_ API in Jenkins.
Other CI integrations will be supported in the future, after the _publications_ API will be implemented on their end.
> Gradle Plugin - New "ALL_PUBLICATIONS" parameter

- build-info-client/src/main/java/org/jfrog/build/client/ArtifactoryHttpClient.java
- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/DockerUtils.java
- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/types/DockerImage.java
-----
Resolves https://github.com/jfrog/jenkins-artifactory-plugin/issues/420
> NoSuchMethodError is thrown using IOUtils.toString(in, StandardCharsets.UTF_8)

- Jenkinsfile
-----
Setting the next development version should set the next build-info version too:
https://github.com/jfrog/build-info/commit/5cd06acba9e5408cc0c671ab128e58889e4e1026#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19R8
> Release script - fix set next development version

- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
-----
Resolves https://github.com/jfrog/jenkins-artifactory-plugin/issues/415
Currently the command executor for Linux, run each command separately:
```java
Runtime.getRuntime().exec(args.toArray(new String[0]), env, execDir)
```
However, it doesn't work for multiple commands, like commands with `&&`.
To support multiple commands, the command executor can get for both Linux and Mac 3 arguments:
1. `/bin/bash`
2. `-c`
3. The commands to run in 1 string
> BI-562 - Command executor in Linux does not accept multiple commands

- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
-----
Revert `/bin/bash` to `/bin/sh` following @saper's  [review](https://github.com/jfrog/build-info/pull/452#discussion_r570107488).
> BI-562 - Command executor in Linux does not accept multiple commands - fix

- build-info-extractor/src/main/java/org/jfrog/build/extractor/issuesCollection/IssuesCollector.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/issuesCollection/IssuesCollectorTest.java
> BI-565 collect issues should ignore errors when the revision of the previous build info doesn't exist

- README.md
> Update Artifactory image URL to releases-docker.jfrog.io

- build-info-client/src/main/java/org/jfrog/build/client/ArtifactoryHttpClient.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientBuilderBase.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBaseClient.java
-----
To allow setting the SSL context in the Intelij IDEA plugin, lets add a setter in the base Artifactory HTTP client.
> Allow setting the SSL Context in the base client

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoRun.java
- build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/extractor/GoExtractorTest.java
-----
Since go 1.16, build commands like go build and go test no longer modify go.mod and go.sum by default. Instead, they report an error if a module requirement or checksum needs to be added or updated.
Related PR: https://github.com/jfrog/jenkins-artifactory-plugin/pull/444
> Fix - tests fail after upgrade go version to 1.16

- appveyor.yml
> Upgrade go version to 1.15 for appveyor linux tests

- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/extractor/DockerPush.java
> Bugfix - NPE is thrown if Docker image is not found in Artifactory

- build.gradle
- ci/pipelines.release.yml
-----
* Sign JARs automatically in the release job
* Release JARs to Maven Central in the end
> Sign JARs before publishing

- build.gradle
- ci/pipelines.release.yml
-----
Remove `env -i` command when running a command that requires signing.
The reason is that `env -i MULTILINE_ENV_KEY=$MULTILINE_ENV_KEY` returns an error.
> Fix signing

- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/Issue.java
-----
Top available issue severity should be critical. 
This issue effects dependency trees with critical top issue (red), however the top issue displayed is high (orange):
> IDE scan - fix top issue severity

- build-info-api/src/main/java/org/jfrog/build/api/Build.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBuildInfoClient.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/retention/Utils.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBuildInfoClientTest.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/issuesCollection/IssuesCollectorTest.java
-----
Creates a platform URL after published build.
Related PR: https://github.com/jfrog/jenkins-artifactory-plugin/pull/455
> Support Jfrog platform URL for published build

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
- build-info-extractor-ivy/src/main/java/org/jfrog/build/extractor/listener/ArtifactoryBuildListener.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/packageManager/PackageManagerExtractor.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/packageManager/PackageManagerUtils.java
-----
When building npm, Go, Pip, and NuGet projects, we should allow collecting the environment during the extractor process.
> Bugfix - env not collect in npm, Go, Pip, and NuGet builds

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleModuleExtractor.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Consts.java
- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/GradlePluginTest.java
- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Utils.java
- build-info-extractor-gradle/src/test/resources/integration/buildinfo.properties.deployer
- build-info-extractor-gradle/src/test/resources/integration/buildinfo.properties.resolver
> Gradle - Collect build info when publisher is missing

- README.md
-----
README.md has some commands that start with `>`, which may cause unexpected results E.G.:
Bash may interpreter command which starts with `>` as overwrite to a File using the Redirection Operator
> Remove `>` from README.md

- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/extractor/DockerPush.java
- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/types/DockerImage.java
-----
The Jenkins Artifactory Plugin supports Docker push to Artifactory. After the push was successful, it sets each layer with build-name & build-number properties. if the build-name or build-number container special characters, the set properties will fail therefore we need to encode each property key and value.
Moreover, for "fat-manifest" images, the wrong path was returned which cause us to search the image manifest in the wrong place Artifactory.
> Fix Docker push bugs cause by Restructuring Artifactory APIs.

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/GetRepositoriesKeys.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/response/GetRepositoriesKeyResponse.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/response/GetRepositoriesResponse.java
-----
The response of `GET api/repositories`is a list of repositories. Therefore the response value of GetRepositoriesKey should be a list.
> Fix deserialization error in GetRepositoriesKeys

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/SendBuildRetention.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryManagerTest.java
> Bugfix - build retention service has an empty body

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/JFrogService.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/DownloadToFile.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/util/DownloadTest.java
-----
All JFrog services ignore response with zero content length, this isn't fit to upload service, as it stops the download flow before reaching file creation. Therefore it was removed.
Fixes  https://github.com/jfrog/jenkins-artifactory-plugin/issues/490
> Bugfix - Error when trying to download an empty (zero bytes size) file

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/ArtifactoryManager.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/Upload.java
-----
Before this fix, deployed artifacts were logging without full URL:
```
[consumer_0] Deploying artifact: bar-generic/example.gif;system-api=https%3A%2F%2Ffishtank.com;package=mccApp;build.timestamp=1622367545908;state=incremental;build.name=as;build.number=1;version=99.0.3.2
```
After this PR changes :
```
[consumer_0] Deploying artifact: https://ecosysjfrog.jfrog.io/artifactory/bar-generic/example.gif
```
Moreover, the printing log messages were duplicated, one for checksum deploy and the second time for the casual upload(in case checksum deploy failed)
Resolve: https://github.com/jfrog/build-info/issues/508
> Bugfix - deploy file logging isn't showing full URL

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/JFrogService.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/Download.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/ScanBuild.java
-----
Same as https://github.com/jfrog/build-info/pull/450
Resolves https://github.com/jfrog/jenkins-artifactory-plugin/issues/506
Use [IOUtils.toString(InputStream,String)](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/IOUtils.html#toString-java.io.InputStream-java.lang.String-) instead of [IOUtils.toString(InputStream, Charset)](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/IOUtils.html#toString-java.io.InputStream-java.nio.charset.Charset-) to support usage of Apache Commons older than 2.3. This issue may occur in the Jenkins plugin whereby Apache Commons 2.2 used in the classloader from one of the other plugins.
> Fix NoSuchMethodError when using IOUtils.toString(InputStream, Charset)

- build.gradle
-----
Resolves https://github.com/jfrog/build-info/issues/522
file-specs-java 1.0.2 is uploaded to Maven Central. Let's include it in the build and make sure it downloaded from Maven Central and not from https://releases.jfrog.io.
> Update file-specs-java to 1.0.2

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/PublishBuildInfo.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/ReportUsage.java
-----
Related: https://github.com/jfrog/jenkins-artifactory-plugin/pull/525
> Add encode boolean to createBuildInfoUrl func

- .github/workflows/gradle.yml
- README.md
-----
Resolves https://github.com/jfrog/build-info/issues/518
Check every 4 hours if the `build-info-extractor-gradle` version in the Maven Central is newer than the latest published in the Gradle gallery. If it does, update the version in the Gradle Gallery.
> Publish Gradle plugin to Gradle Gallery

- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/DockerUtils.java
- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/extractor/BuildDockerCreator.java
- build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/types/NpmPackageInfo.java
- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/types/NugetProjectAssets.java
- build-info-extractor-pip/src/main/java/org/jfrog/build/extractor/pip/extractor/DependenciesCache.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ModuleExtractorUtils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/JFrogService.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/deploy/DeployableArtifactsUtils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/JsonSerializer.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/JsonUtils.java
-----
Resolves https://github.com/jfrog/jenkins-artifactory-plugin/issues/522#issuecomment-880781341
Fix the following issue:
> Unrecognized field "targetRepository" (class org.jfrog.build.client.DeployableArtifactDetail), not marked as ignorable (5 known properties: "sourcePath", "deploySucceeded", "artifactDest", "sha1", "sha256"])
at [Source: (File); line: 1, column: 529] (through reference chain: java.util.LinkedHashMap["charging-notification-java-client"]->java.util.ArrayList[0]->org.jfrog.build.client.DeployableArtifactDetail["targetRepository"])
> Fail to deserialize deployable artifacts

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java
-----
If Maven publication with `components.java` exist, but there are no JARs produced in the build, don't fail the build.
Instead log the returned exception with information about the project and the publication.
For example:
>  Illegal state detected at Maven publication: 'mavenJava', project ':api': Artifact api.jar wasn't produced by this build.
> Gradle - skip uploading JAR if no jar produced in build

- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/GradlePluginTest.java
- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Utils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/ArtifactoryManager.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/DeleteBuilds.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/GetAllBuildNumbers.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/request/DeleteBuildsRequest.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/response/GetAllBuildNumbersResponse.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryManagerTest.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/issuesCollection/IssuesCollectorTest.java
- build-info-extractor/src/testFixtures/java/org/jfrog/build/IntegrationTestsBase.java
* Add build delete service
* Delete published tests build
* Tests' build number changed from const-number to timestamp
-----
Related: https://github.com/jfrog/jenkins-artifactory-plugin/pull/529
> Fix tests collisions caused by multiple runs

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/DependenciesDownloaderHelper.java
-----
Supersedes https://github.com/jfrog/build-info/pull/534
Resolves #533 
Headers comparison should not be case-sensitive.
> Make download headers comparisons case insensitive

- build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmBuildInfoExtractor.java
- build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmDependencyTree.java
- build-info-extractor-npm/src/test/java/org/jfrog/build/extractor/npm/extractor/NpmDependencyTreeTest.java
-----
`package.json` files are allowed to be without name and version nodes. Currently, the code throws NPE in such cases.
If `name` is missing, use the directory name as the project name.
If only `version` is missing, use the name without the version as the project name.
Otherwise, use <name>:<version> as the project name.
> Allow npm projects without name and versions

- build-info-client/src/main/java/org/jfrog/build/client/artifactoryXrayResponse/Issue.java
-----
Resolves https://github.com/jfrog/jenkins-artifactory-plugin/issues/560
To support older Xray versions, we should accept either "security" and "Security" issue types. Same for the license type.
> Build scan - allow getIssueType to be case-insensitive

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
- build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/GoDriverTest.java
-----
Add 2 new commands to the Go Driver:
1. getUsedModules - run `go list -f "{{with .Module}}{{.Path}} {{.Version}}{{end}}" all`
2. modTidy - run `go mod tidy`
> Add getUsedModules and modTidy to GoDriver

- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/Artifact.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/DependencyTree.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/GeneralInfo.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/License.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/scan/DependencyTreeTest.java
> Add support for new Xray graph scan (Xray java client)

- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/DependencyTree.java
> Add projectSetting field to Dependency tree node

- build-info-api/src/main/java/org/jfrog/build/api/Artifact.java
- build-info-api/src/main/java/org/jfrog/build/api/BaseBuildFileBean.java
- build-info-api/src/main/java/org/jfrog/build/api/Dependency.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/DependenciesDownloaderHelper.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/util/DownloadTest.java
-----
Following issue: https://github.com/jfrog/jenkins-artifactory-plugin/issues/564 where downloading artifact from Artifactory multiple times from different paths shows only one artifact in the build-info.json.
In addition, download a dependency across different file-specs causes to duplicate the same dependency in the build-info.json
Related: https://github.com/jfrog/jenkins-artifactory-plugin/pull/571
> Bugfix - Build-info ignores duplicate artifacts checksum

- release/pipelines.release.yml
- release/pipelines.snapshot.yml
-----
* `jfrog` -> `jf`
* Enable build scan
* Delete entplus_deployer server after downloading jfrog cli
> Improve CI scripts

- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Utils.java
- build-info-extractor-gradle/src/test/resources/integration/gradle-example-ci-server/api/build.gradle
- build-info-extractor-gradle/src/test/resources/integration/gradle-example-ci-server/services/webservice/build.gradle
- build-info-extractor-gradle/src/test/resources/integration/gradle-example-publish/api/build.gradle
- build-info-extractor-gradle/src/test/resources/integration/gradle-example-publish/services/webservice/build.gradle
- build-info-extractor-gradle/src/test/resources/integration/gradle-example/api/build.gradle
- build-info-extractor-gradle/src/test/resources/integration/gradle-example/services/webservice/build.gradle
- build-info-extractor-gradle/src/test/resources/integration/gradle-kts-example-publish/api/build.gradle.kts
- build-info-extractor-gradle/src/test/resources/integration/gradle-kts-example-publish/services/webservice/build.gradle.kts
- build-info-parent/pom.xml
-----
Followup https://github.com/jfrog/build-info/pull/580
Currently, the Gradle tests are failing since they use commons-lang:2.4. 
Complete the migration from 2.4 to 3.12.
> Fix Gradle tests

- build-info-extractor-gradle/src/test/resources/integration/buildinfo.properties.deployer
- build-info-extractor-gradle/src/test/resources/integration/buildinfo.properties.resolver
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientProperties.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/PrefixPropertyHandler.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/client/DeploymentUrlUtilsTest.java
-----
This PR includes a backward-compatible for older versions, which uses the deprecated property.
Related PR:
* https://github.com/jfrog/jenkins-artifactory-plugin/pull/578
> Deprecate 'artifactory.' property prefix.

- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/DockerJavaWrapper.java
-----
As a result of, https://github.com/jfrog/build-info/pull/580 changes the method `isEmpty` has changed in Lang version 2.0. and It is no longer trims the String.
That functionality is available in isBlank().
> Replace !isEmpty with isNotBlank

- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/GradlePluginTest.java
- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Utils.java
- build-info-extractor-gradle/src/test/resources/integration/gradle-example-publish/build.gradle
- build-info-extractor-gradle/src/test/resources/integration/gradle-kts-example-publish/build.gradle.kts
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/DeploymentUrlUtils.java
-----
Fixes https://github.com/jfrog/build-info/issues/567
> Bugfix - Multi Values Properties Set

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoZipBallStreamer.java
- build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/extractor/GoZipBallStreamerTest.java
> Add support for v2 compatible go projects with submodule as root

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientConfigurationFields.java
-----
`isPublishArtifacts` disable build-info from generating `deployable.artifacts.json`.
This file is used by maven late artifacts deploy to know which artifact to deploy to where.
This PR replace isPublishArtifacts by adding a new property instead.
Related PR: https://github.com/jfrog/build-info-go/pull/26
> Fix maven late deploy

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
- build-info-extractor-ivy/src/main/java/org/jfrog/build/extractor/listener/ArtifactoryBuildListener.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoModelPropertyResolver.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/BuildInfoFields.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/GitUtils.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/util/GitUtilsTest.java
- build.gradle
> Add vcs.branch and vcs commit message to VCS build-info details

- build-info-api/src/main/java/org/jfrog/build/api/util/FileChecksumCalculator.java
- build-info-api/src/test/java/org/jfrog/build/api/FileChecksumCalculatorTest.java
- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoCommand.java
- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoPublish.java
- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoRun.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleModuleExtractor.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperConfigurations.java
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java
- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Utils.java
- build-info-extractor-ivy/src/main/java/org/jfrog/build/extractor/trigger/ArtifactoryBuildInfoTrigger.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/extractor/NugetRun.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/deploy/DeployDetails.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/DependenciesDownloaderHelper.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/DependenciesDownloaderImpl.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/spec/UploadSpecHelper.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/ci/FileChecksumCalculatorTest.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/util/DownloadTest.java
- build.gradle
-----
* Add sha256 field in Gradle builds.
* Use global costs for "MD5", "SHA1", and "SHA256".
* Use [Amazon Corretto Crypto Provider](https://github.com/corretto/amazon-corretto-crypto-provider) library to get accelerated checksum calculations on Linux64 machines. In another machines, it will fall back to the default Java-native behavior - see for example https://github.com/corretto/amazon-corretto-crypto-provider/issues/41#issuecomment-738963540
> Calculate SHA256 in Gradle builds

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/GitUtils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/issuesCollection/IssuesCollector.java
- build.gradle
> Remove JGIT from source code

- release/pipelines.release.yml
- release/pipelines.snapshot.yml
- release/specs/prod-rbc-filespec.json
-----
* Distribute Gradle extractor to releases.
* Use audit with --fail-false
* Install CLI
> Release scripts - minor improvements and distribute Gradle

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/spec/SpecsHelper.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/spec/UploadSpecHelper.java
-----
The sha256 property is missing in the upload command.
Related: https://github.com/jfrog/jenkins-artifactory-plugin/pull/615
> Bugfix - Add missing sha2 on uploaded files

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
-----
Allow insecureTls configuration in the Gradle Artifactory plugin.
Usage:
```groovy
artifactory {
clientConfig.insecureTls = true
}
```
> Gradle - Support insecure TLS

- build-info-api/src/main/java/org/jfrog/build/api/builder/BuildInfoBuilder.java
- build-info-api/src/main/java/org/jfrog/build/api/builder/BuildInfoMavenBuilder.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
-----
Verify that the artifact type is less than 64 characters.
If it's longer, don't use classifier or extension as type.
Fixing https://github.com/jfrog/artifactory-maven-plugin/issues/29
> Verify artifact type limit and add project support for maven

- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/types/DockerImage.java
-----
**Background**
Currently, there are at least 2 ways to configure the Docker registry URL: 
1. Using a reverse proxy or using the full path to the repository: acme-docker-local.jfrog.io. 
2. Using URL to the Docker repository: acme.jfrog.io/docker-local
**Expected**
In the generated build-info, the module ID should be `<image-name>/<image-tag>`.
**Actual**
When configuring URL to Docker repository as a Docker registry, the module ID, in this case: `docker-local/<image-name>/<image-tag>`.
> Fix Docker module name in build-info

- build-info-api/src/main/java/org/jfrog/build/api/builder/BuildInfoBuilder.java
- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Utils.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoModelPropertyResolver.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/builder/BuildInfoBuilder.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/builder/BuildInfoMavenBuilder.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/BuildInfo.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/GetAllBuildNumbers.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/GetBuildInfo.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/PublishBuildInfo.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/SendBuildRetention.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/SendModuleInfo.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/StageBuild.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/UrlUtils.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildExtractorUtilsTest.java
-----
Fix https://github.com/jfrog/jenkins-artifactory-plugin/issues/576
Fix https://github.com/jfrog/jenkins-artifactory-plugin/issues/611
To support using build projects in Maven UI jobs in Jenkins Artifactory plugin, this PR does the following:
* Add the project in BuildInfoModelPropertyResolver.
* Fix the created build-info URL when using projects in all cases.
*  If Artifactory's URL and the project key were provided, the `createBuildInfoUrl` will try to guess the platform URL from Artifactory URL.
* The URL contained `?project=<project-key>` query param instead of `?buildRepo=<project-key>-build-info` param.
> Improve support for Maven projects and fix build-info URL

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoDependencyTree.java
- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoRun.java
-----
Run `go list -f {{with .Module}}{{.Path}} {{.Version}}{{end}} all` to filter unused dependencies in Go builds.
Most of the code copied from https://github.com/jfrog/ide-plugins-common/blob/1.11.0/src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java#L103. After the release we should delete duplicated code in ide-plugins-common.
> Filter out unused dependencies in Go builds

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
> Configure proxy when publishing build info

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoDependencyTree.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/DependencyTree.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/scan/DependencyTreeTest.java
-----
Move `hasLoop` to DependencyTree.java in order to reuse it in the Intellij IDEA plugin.
> Move hasLoop to DependencyTree.java

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
-----
Fixes: https://github.com/jfrog/jfrog-cli/issues/1348
> Bugfix - Limit 'mvn deploy' to work with only install/deploy phases

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoModelPropertyResolver.java
-----
Resolves https://github.com/jfrog/jenkins-artifactory-plugin/issues/655
Resolves https://github.com/jfrog/jfrog-cli/issues/1483
StringUtils.firstNonBlank introduced in 3.8, almost 4 years ago. In some cases, an older commons-lang3 jar may take precedence in the classpath. As a result, a `NoSuchMethodError` exception may appear.
> Remove usage of StringUtils.firstNonBlank

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/GitUtils.java
-----
When checking out to a specific hash and reaching a "detached head" state, there is no actual branch to be found. This commit changes the warning to a debug log.
> Remove warning about missing branch

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/ExecuteUserPlugin.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/GetUserPluginInfo.java
This wrong endpoints seem to have been used since
67cefb286471634b88e104efe2543ad088010471.
https://github.com/jfrog/jenkins-artifactory-plugin/issues/659
-----
> Bugfix - Use the correct plugins endpoints

- build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildExtractorUtilsTest.java
-----
The build info URL for a given platform URL should be:
`https://myartifactory.com/ui/builds/<build-name>/<build-number>/<timestamp>/published?buildRepo=<project-key>-build-info&projectKey=<project-key>`
However, currently it is:
`https://myartifactory.com/ui/builds/<build-name>/<build-number>/<timestamp>/published?buildRepo=<project-key>-build-info`
> When project provided, add projectKey to build info URL

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
- build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/GoDriverTest.java
- build-info-extractor-go/src/test/resources/org/jfrog/build/extractor/project1-err/go.mod
- build-info-extractor-go/src/test/resources/org/jfrog/build/extractor/project1-err/main.go
-----
Resolves https://github.com/jfrog/jfrog-idea-plugin/issues/208
Allow adding `-e` parameter to `go mod tidy`.
> Allow ignoring errors in "go mod tidy"

- build.gradle
-----
[com.gradle.plugin-publish:1.0.0-rc-1](https://plugins.gradle.org/plugin/com.gradle.plugin-publish/1.0.0-rc-1) contains some breaking changes. Since this is a release-candidate and not an official release, we should stick with major 0 for now.
> Fix compilation by using plugin-publish-plugin major 0

- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/Cve.java
-----
The Cve class is used by the JFrog IDEA plugin's cache. An attempt to deserialize a cache object will fail with the following error:
> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.jfrog.build.extractor.scan.Cve` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
> Bugfix - Cve should have an empty constructor

- build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/DockerUtils.java
- build-info-extractor-docker/src/test/java/org/jfrog/build/extractor/docker/extractor/DockerUtilsTest.java
-----
The function `getArtManifestPath` generates four potential paths to search docker manifests in Artifactory
The 'Assume proxy-less' path is being generated incorrectly.
> Fix Docker Manifest path for collecting build-info

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelper.java
- build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Utils.java
-----
Using the Artifactory convention in allProjects{ ... } may cause the artifacts not to have build info properties, such as build.name and build.number:
```groovy
allProjects {
artifactory {
// ...
}
}
```
Notice - it is not recommended and not documented to put the artifactory convention in the "allProjects" scope. It should be in the root project:
```groovy
allProjects {
// ...
}
artifactory {
// ...
}
```
> Bugfix - Missing Gradle build-info props on artifacts

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/AqlHelper.java
-----
This PR is to fix a bug we've encountered on a group of Jenkins pipelines using the jenkins-artifactory-plugin.  The gist is that a call to download artifacts through the jenkins-artifactory-plugin results in a call to `AqlHelper` with a `FilesGroup` that doesn't have a `build` set.
This causes `fetchBuildArtifactsSha1` to send a broken AQL request to Artifactory, that ultimately times out (in our case, causing a 504).  It used to work when the call went through `PatternAqlHelper`, which did the search but didn't do the additional filtering by build.
I've posted an example input, the rough callstack to get to this point, and the broken AQL that was sent from `fetchBuildArtifactsSha1` below:
```groovy
artifactoryServer.download(
failNoOp: false,
spec: """{
"files": [
{
"pattern": …
```
> Bugfix - Broken AQL request when build is not defined in FilesGroup

- build.gradle
-----
i see the dependency httpclient is 4.5.13, but httpcore is 4.4.5, i  suggest that their versions should be consistent.
> upgrade httpcore from 4.4.5 to 4.4.13

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
-----
Support JFrog Projects in Gradle
> gradle extractor - Add support for JFrog Projects

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
-----
Resolves: 
* https://github.com/jfrog/jfrog-cli/issues/1621
*  https://github.com/jfrog/jfrog-cli/issues/1721
Since maven-install-plugin 3.0.0, the module metadata is not populated a ProjectArtifactMetadata. As a result, we can't extract the information about the pom.xml artifact in the same way before.
This PR extracts the information about pom.xml from the project's artifact.
> Pom doesn't get deployed using Maven Install plugin 3+

- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/executor/CommandExecutorTest.java
-----
Resolve an issue in the JFrog IDEA plugin whereby Go executable path is under `C:\program files` directory in Windows.
> CommandExecutor - Support executable path with spaces

- build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClientBuilder.java
-----
Set the connection request timeout to avoid infinite timeout during connection requests.
> Set the connection request timeout

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/DeploymentUrlUtils.java
-----
Fix https://github.com/jfrog/teamcity-artifactory-plugin/issues/127
> Skip null matrix values in buildMatrixParamsString

- build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/DependencyTree.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/scan/DependencyTreeTest.java
-----
Undo the change here: https://github.com/jfrog/build-info/pull/659/files#diff-0d5319592f114ad883c7ad2d602e0b187f22d6e4a9087788f4551b4cc1d5ba26R130 and yet support Java 11.
> Make getChildren and getNodes return DependencyTree

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoDependencyTree.java
- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoRun.java
- build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/GoDriverTest.java
- build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/extractor/GoDependencyTreeTest.java
-----
Dependency for: https://github.com/jfrog/ide-plugins-common/pull/93
This fix is for the JFrog IDEA plugin and potentially for the Go build-info extractor - 
Allow providing the dontBuildVcs flag, which can be used to skip VCS stamping to bypass the following error:
> IOException: error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping.
> Allow skip VCS stamping in Go

- build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClient.java
-----
Required for https://github.com/jfrog/build-info/pull/693
Handle intermittent errors caused in Distribution:
> Gradle suite > Gradle test > org.jfrog.build.extractor.clientConfiguration.client.RemoteDistributionManagerTest > asyncDistributionTest FAILED
java.io.IOException: JFrog service failed. Received 500: {"detail":"Artifactory bad response at url: api/release/store","message":"Artifactory: Cannot invoke \"org.artifactory.repo.ReleaseBundlesRepo.accepts(org.artifactory.repo.RepoPath)\" because \"repo\" is null","status_code":500}
> Retry on errors 500

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/extractor/NugetRun.java
-----
This save is needed for bamboo-artifactory-plugin
> Add build info json save to target directory

- build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClient.java
-----
Adds the option to pass a context object to the PreemptiveHttpClient's execute function.
The context object contains a lot of information about the processed request.
It can be used to detect HTTP redirection.
> Add PreemptiveHttpClient execute with context

- build-info-extractor-maven3/src/main/resources/META-INF/plexus/components.xml
-----
Fixes this exception:
```
[main] ERROR org.apache.maven.cli.MavenCli - NullPointerException
java.lang.NullPointerException
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:296)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:278)
at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver.resolveArtifacts (ArtifactoryEclipseArtifactResolver.java:56)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:255)
```
> Fix missing fields for maven 3.9.0

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
- build-info-extractor-ivy/src/main/java/org/jfrog/build/extractor/listener/ArtifactoryBuildListener.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractor.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/PatternMatcher.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/packageManager/PackageManagerExtractor.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/packageManager/PackageManagerUtils.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildExtractorUtilsTest.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/packageManager/PackageManagerUtilsTest.java
-----
Prior to this PR, build-info properties were filtered only for environment variables and system properties.
The PR moves all filter logic into one place and performs exclude/include logic for all properties, including:
1. Environment variables (including properties with `buildInfo.env` prefix)
2. System properties
3. Properties from file
4. Build-info modules properties
5. Exclude not just the key but also the value of properties
> Filter build-info and modules properties

- build-info-extractor-maven3/src/main/resources/META-INF/plexus/components.xml
-----
Should fix https://github.com/jfrog/jfrog-cli/issues/1863
```
[main] ERROR org.apache.maven.cli.MavenCli - NullPointerException
java.lang.NullPointerException
at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve (DefaultMetadataResolver.java:213)
at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata (DefaultMetadataResolver.java:198)
```
> Fix missing Maven 3.9.0 requirement field

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/ReportUsage.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/usageReport/ClientIdUsageReporter.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/usageReport/UsageReporter.java
-----
Add client ID to the usage report - we use the first network interface MAC address we found as the client ID.
> Add Client ID to the usage report

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/ArtifactoryProjectBuilder.java
This PR is the continuation of the original PR https://github.com/jfrog/build-info/pull/683 that was reverted because of authentication issues.
This PR adds setting authentication and proxy details if configured, the one missing bit looking at the provided issues in comment https://github.com/jfrog/build-info/pull/683#issuecomment-1451437279
Background info:
The dummy repository is added to allow for the resolution of depedencies using the jfrog cli resolver configuration for Maven. Some maven build plugins, like the org.codehaus.mojo:versions-maven-plugin will try to resolve artifacts using this dummy repository but will always fail.
This PR implements a solution that allows maven build plugins to resolve artifacts using the jfrog cli resolver configuration by configuring the snapshot …
> Remove the need for setting up a dummy repository

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/ArtifactoryManager.java
-----
Wrong condition - missed the LATEST option
> Fix getLatestBuildNumber wrong condition

- build-info-client/src/main/java/org/jfrog/build/client/JFrogHttpClient.java
- build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClient.java
- build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClientBuilder.java
- build-info-client/src/test/java/org/jfrog/build/client/PreemptiveHttpClientBuilderTest.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/AccessManager.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/GetBrowserLoginRequestToken.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/SendBrowserLoginRequest.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/Utils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/response/CreateAccessTokenResponse.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/AccessManagerTest.java
- build.gradle
-----
Required for:
* https://github.com/jfrog/jfrog-idea-plugin/pull/359
Add 2 new APIs required for SSO login:
1. SendBrowserLoginRequest
2. GetBrowserLoginRequestToken
Allow anonymous access in JFrog Access REST APIs.
> Support browser login requests

- build-info-api/src/main/java/org/jfrog/build/api/Agent.java
- build-info-api/src/main/java/org/jfrog/build/api/Artifact.java
- build-info-api/src/main/java/org/jfrog/build/api/Build.java
- build-info-api/src/main/java/org/jfrog/build/api/BuildAgent.java
- build-info-api/src/main/java/org/jfrog/build/api/BuildBean.java
- build-info-api/src/main/java/org/jfrog/build/api/BuildRetention.java
- build-info-api/src/main/java/org/jfrog/build/api/Dependency.java
- build-info-api/src/main/java/org/jfrog/build/api/MatrixParameter.java
- build-info-api/src/main/java/org/jfrog/build/api/Module.java
- build-info-api/src/main/java/org/jfrog/build/api/Vcs.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Agent.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Artifact.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/BuildAgent.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/BuildInfo.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/BuildRetention.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Dependency.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Module.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Vcs.java
- build.gradle
> Remove XStream dependency

- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
> Fix Javadoc generation

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ProjectsEvaluatedBuildListener.groovy
-----
When the Gradle Java plugin is not applied, Legacy Gradle Archive configurations are not automatically collected and published in CI mode.
> Gradle legacy Archives are not published

- build-info-extractor-pip/src/test/resources/org/jfrog/build/extractor/requirementsProject/requirements.txt
- build-info-extractor-pip/src/test/resources/org/jfrog/build/extractor/setuppyProject/setup.py
-----
PyYaml < 6.0.1 is not compatible with Cython>=3.0, which released on [July 17, 2023](https://github.com/cython/cython/releases/tag/3.0.0).
This PR fixes the following stacktrace in the tests:
>
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
main()
File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel …
> Fix Python tests

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ProjectsEvaluatedBuildListener.groovy
This reverts commit 9c66c86e37d103f314008c5a3d36137bc81b2a13.
-----
The decision to revert the change in issue #748 was made after realizing that enforcing the "java" plugin was preventing projects in every Gradle version from publishing their JARs.
> Revert "Gradle legacy Archives are not published (#748)"

- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
- build-info-extractor/src/testFixtures/java/org/jfrog/build/IntegrationTestsBase.java
> Improve handling of spaces in command execution utility on Windows

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
-----
In Maven builds, the absence of a pom.xml file in the working directory might result in the following error:
```
java.lang.IllegalArgumentException: File not found: null
at org.jfrog.build.extractor.clientConfiguration.deploy.DeployDetails$Builder.build (DeployDetails.java:154)
at org.jfrog.build.extractor.maven.BuildInfoRecorder.addDeployableArtifact (BuildInfoRecorder.java:577)
at org.jfrog.build.extractor.maven.BuildInfoRecorder.addPomArtifact (BuildInfoRecorder.java:540)
```
To replicate this problem, use the Maven deploy plugin to deploy a file from a directory lacking pom.xml. For instance:
```sh
jf mvn org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy-file -Dfile=README -Durl=https://acme.jfrog.io/artifactory/default-maven-local/ -DgroupId=groupId …
```
> Skip collecting pom if not exists

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
- build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/GoDriverTest.java
> Resolved Issue with Running 'go' Command on Windows in Paths with Spaces

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/encryption/PropertyEncryptor.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfigurationTest.java
> Escape backslashes so that they won't be removed when loading the properties

- build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildExtractorUtilsTest.java
-----
Fix https://github.com/jfrog/jfrog-cli/issues/2373
The setup for the client should prioritize Java system properties over the [default properties](https://github.com/jfrog/jfrog-cli-core/blob/c6fd4b1140b46298b9f87f988e3836b7863adc46/artifactory/utils/buildinfoproperties.go#L81C1-L81C1) set by the JFrog CLI. Take this command, for instance, where the JFrog CLI specifies `artifactory.publish.artifacts=true`, but a conflicting false value is set by a system property:
```sh
jf mvn clean install -Dartifactory.publish.artifacts=false
```
In this case, the system property should take precedence over the default value from the JFrog CLI.
> Client configuration should prefer system properties

- build-info-api/src/main/java/org/jfrog/build/api/BuildInfoConfigProperties.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/BuildInfoConfigProperties.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/packageManager/PackageManagerUtils.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildExtractorUtilsTest.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/packageManager/PackageManagerUtilsTest.java
-----
Instead of setting the `buildInfoConfig.propertiesFileKey` and `buildInfoConfig.propertiesFileKeyIvy` environment variables, set the following environment variables:
`PROPERTIES_FILE_KEY` and `PROPERTIES_FILE_KEY_IV`.
> Encryption keys aren't passed in Linux Jenkins agents

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
- build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/GoDriverTest.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/executor/CommandExecutorTest.java
-----
When executing a command on Windows, add its directory path to the Path environment variable and execute it using its name. We do that to avoid passing an executable path that contains spaces, which causes parsing issues in Windows CMD.
> Fix running executables with spaces in their paths in Windows

- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
-----
Add persistToPropertiesFile overload to enable external stream. 
Relate to:
* https://github.com/jfrog/jenkins-artifactory-plugin/pull/923
> Add persistToPropertiesFile overload

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoVersionUtils.java
> Fix getMajorProjectVersion Regex pattern in Go

- build-info-extractor-maven3/src/test/java/org/jfrog/build/extractor/maven/resolver/ArtifactoryResolutionTest.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ProxySelector.java
-----
Fix https://github.com/jfrog/jfrog-cli/issues/2638
The `NO_PROXY` pattern for specifying multiple hosts is a comma-separated list:
`NO_PROXY=host1.jfrog.io,host2.jfrog.io`
https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html
In Java, the system property `http.nonProxyHosts` uses a pipe-separated list for multiple hosts:
`-Dhttp.nonProxyHosts=host1.jfrog.io|host2.jfrog.io`
https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
This pull request adjusts the `http.nonProxyHosts` value by replacing commas with pipes.
> Support multiple no proxy hosts in Maven

- build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoVersionUtils.java
- build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/extractor/GoVersionUtilsTest.java
> Fix VERSION_PATTERN Regex pattern in Go

- build-info-api/src/main/java/org/jfrog/build/api/Artifact.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/builder/ArtifactBuilder.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Artifact.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildExtractorUtilsTest.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/ci/ArtifactTest.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/ci/BuildInfoMavenBuilderTest.java
- build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/AccessManagerTest.java
- build-info-extractor/src/testFixtures/java/org/jfrog/build/IntegrationTestsBase.java
-----
Added an existing build-info field from build-info-go to enable its use in Artifactory as well.
> Add original deployment repository field

- build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/extractor/NugetRun.java
- build-info-extractor-nuget/src/test/java/org/jfrog/build/extractor/nuget/extractor/NugetExtractorTest.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientProperties.java
-----
```
<packageSources>
<add key="JFrogCli" value="%s" protocolVersion="%s" **allowInsecureConnections**="%v"/>
</packageSources>
```
The [latest .NET 6 release](https://versionsof.net/core/6.0/6.0.36/) introduces changes to NuGet that now restrict the use of insecure connections for package sources unless a specific flag is enabled.
This update resolves the failing tests by adding the required flag for cases where it is necessary. This flag is primarily intended for testing purposes to allow use with local sources and should not be enabled in production environments.
For the tests this flag is set to true.
If you user would like to overwrite this flag, it can be done via the `nuget.AllowInsecureConnections` prop.
> NuGet - add `allowInsecureConnections` attribute to config

- .github/workflows/integrationTests.yml
-----
Fix .NET installation issues 
Just like - https://github.com/jfrog/jfrog-cli/pull/2808
> Tests - Fix .NET ubuntu installation

- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/ArtifactoryProjectBuilder.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/resolver/ArtifactoryEclipseResolversHelper.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/resolver/ArtifactoryPluginResolution.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/resolver/ArtifactoryResolution.java
- build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/resolver/ResolutionHelper.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
- build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientConfigurationFields.java
- build.gradle
> Support disabling Maven Snapshot dependency Resolution & Set Update Policy

- release/pipelines.release.yml
-----
The `jf audit --fail=false` command is not working as expected and fails the release
Until it will be fixed, we added env var to allow skipping audit
default value is false
> Added conditional statement to skip audit while releasing

- build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
-----
The issue was that when loading properties files with malformed Unicode escape sequences (like `\uxxxx`), the original code would fail with `IllegalArgumentException: Malformed \uxxxx encoding`.
The fix implements a fallback strategy:
- First, try the normal properties loading
- If that fails with `IllegalArgumentException`, try loading with explicit UTF-8 encoding
- If that also fails, continue with empty properties rather than failing the entire build
> Fix for Jenkins Malformed encoding

- build.gradle
-----
unable to release since the response from sona type is 401 and probably it is nothing to do with credentials
sonatype { nexusUrl ... snapshotRepositoryUrl ... } block is required to explicitly set the Nexus and snapshot repository URLs for the new OSSRH publishing API. The older sonatype() shortcut uses default URLs, which may not work with the updated Sonatype Central
> Updated sonatype with nexus URL

- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/ArtifactoryPluginBase.groovy
- build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ProjectsEvaluatedBuildListener.groovy
- build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
Problem-
A user is experiencing an issue where the dependencies of their Android project are not being captured in the build-info.json file when using the JFrog CLI following command. 
1- jf gradle "assembleDebug" --build-name=android-gradle --build-number=1
2- jf rt u "app/build/outputs/apk/debug/app-debug.apk" "demo-gradle-dev/android-sample-app/app-debug.apk" --build-name=android-gradle --build-number=1
3- Jf rt bp android-gradle 1
While this isn't preventing the build from completing, it creates a feeling that the project isn't being built properly.
"assembleDebug" is a gradle build task which lets you build the apk for the staging environment. This task does not enable the module-extractor task which helps to collect the dependencies.
Solution-
by adding artifactoryPublish in the …
> Include dependency metadata in build-info for Android
