build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/BuildInfoBaseTask.java

Set the timeout from the DSL configuration into the artifactory client. Fixes #38

Update client timeout with value from gradle DSL if present

---

README.md

Set of changes that adds JSON schema to README.md as discussed in issue #82.

JSON schema for build-info 

---

README.md

@eyalbe4, 
I reviewed what you merged last night and discovered a few minor issues.  One was a cut-and-paste error where I added the "count" property from the "buildRetention" object to the "licenseControl" object.  The other was the fact that I didn't set additionalProperties to false for the "issues" object's "tracker" and "affectedIssues" sub-objects.

JSON schema nits

---

build.gradle

#95 up-to-date check for jarAll task does not work

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/PlaceholderReplacementUtils.java

https://www.jfrog.com/jira/browse/HAP-823

Fix pattern matching of path on windows platform

---

build-info-api/src/main/java/org/jfrog/build/api/BaseBuildFileBean.java
build-info-api/src/main/java/org/jfrog/build/api/BuildFileBean.java
build-info-api/src/main/java/org/jfrog/build/api/builder/ArtifactBuilder.java
build-info-api/src/main/java/org/jfrog/build/api/builder/DependencyBuilder.java
build-info-api/src/test/java/org/jfrog/build/api/ArtifactTest.java
build-info-api/src/test/java/org/jfrog/build/api/DependencyTest.java
build-info-api/src/test/java/org/jfrog/build/api/builder/ArtifactBuilderTest.java
build-info-api/src/test/java/org/jfrog/build/api/builder/BuildInfoMavenBuilderTest.java
build-info-api/src/test/java/org/jfrog/build/api/builder/DependencyBuilderTest.java

Bare minimum interface changes for future sha256 support in build-info for Artifactory.

RTFACT-6962 - Minimal build-info foundation for Artifactory sha256 support

---

build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/dsl/ArtifactoryPluginConvention.groovy

Fix gradle proxy and buildInfo DSL DoubleDelegateWrapper constructor

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/PublishedItemsHelper.java
build.gradle

Updated Jackson to version 2.9.3

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/IncludeExcludePatterns.java

Precondition for: https://github.com/jfrog/jenkins-artifactory-plugin/pull/74

BI-463 - Declarative syntax for Jenkins Artifactory Plugin

---

build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
build.gradle

Jenkins code:
https://github.com/jfrog/jenkins-artifactory-plugin/pull/85

Maven pipeline - Excluded artifacts in build info

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/spec/SpecsHelper.java

BI 464 - Add the ability to control the number of parallel uploads using File Specs

BI 464 - Add the ability to control the number of parallel uploads using File Specs

---

build.gradle

Upgraded guava, fasterxml.jackson & org.apache.commons to latest versions.

Updated Dependencies

---

build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java

Fixes #91
We are running the changes successfully in our production environment.
See also https://www.jfrog.com/jira/browse/NMAP-33

Non packaging pom project fails to deploy pom file to artifactory #91

---

build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClient.java

This is the kind of messages that end up in build logs when artifactory is fronted by an ALB
```
Invalid cookie header: "Set-Cookie: AWSALB=<Base64>; Expires=Wed, 22 May 2019 02:58:45 GMT; Path=/". Invalid 'expires' attribute: Wed, 22 May 2019 02:58:45 GMT
```

Prevent 'Invalid cookie header' messages

---

build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java

GradleBuildInfoExtractor triggers deprecation warnings when using Gradle 5 with --parallel

---

build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/resolver/ArtifactoryEclipseRepositoryListener.java
build-info-extractor-maven3/src/main/resources/META-INF/plexus/components.xml

Potentially https://github.com/jfrog/jenkins-artifactory-plugin/issues/209.

Maven builds fail with some Maven extensions

---

build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/NpmDriver.java
build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmBuildInfoLogger.java
build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmCommand.java
build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmInstall.java
build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmPublish.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientBuilderBase.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientConfigurationFields.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientProperties.java

Jenkins code: https://github.com/jfrog/jenkins-artifactory-plugin/pull/224
See example here: jfrog/project-examples#190

Allow running npm in a new Java process

---

build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/transformer/PomTransformer.java

Endless loop when calculating nextPomToLoad on Windows with Maven multi module projects.

Artifactory Release Staging results in StackOverflowError

---

build-info-client/src/main/java/org/jfrog/build/client/ArtifactoryHttpClient.java
build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClient.java
build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClientBuilder.java
build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoClientBuilder.java
build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorderLifecycleParticipant.java
build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmBuildInfoExtractor.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientProperties.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBaseClient.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/spec/SpecsHelper.java

*This commit includes refactor PreemptiveHttpClient to be created by a builder.

Mvn3Extractor - Support insecure tls for maven resolution and deployment.

---

build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmPublish.java

Related to:
https://www.jfrog.com/jira/browse/HAP-1319
https://github.com/jfrog/jfrog-cli/issues/622

Npm - Incorrect module name

---

build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/ExtractModuleTask.java

This fixes https://github.com/jfrog/build-info/issues/325

ExtractModuleTask should have a proper getter for moduleFile property

---

build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/util/spec/SpecsHelperIntegrationTest.java

Currently, `SpecsHelperIntegrationTest` output is messy. The test environment prints `testPath`, `uploadSpec`, `downloadSpec` and `expected`.
After this fix, it prints only the `testPath`. This change reduce the tests output from almost 8000 lines to ~2000 lines and make the tests output more readable.
For example, here is a "started" output of a single test, out of dozens:
```
Gradle suite > Gradle test > org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelperIntegrationTest > integrationTests[0](C:\projects\build-info\build-info-extractor\build\resources\test\integration\tests\download\explode, {
"files": [
{
"pattern": "explode/*",
"target": "build-info-tests-local/",
"recursive": "true"
}
]
}, {
"files": [
{
"explode": "true",
"flat": "true",
"aql": {
"items.find": { …
```

Clean up SpecsHelperIntegrationTest

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/gradle_bug_report.md
.github/ISSUE_TEMPLATE/maven_bug_report.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

* Add PR template
* Add Issues templates
* Bug report
* Maven plugin bug report
* Gradle plugin bug report
* Feature request
* question

Add GitHub issues and PR templates

---

build-info-client/src/main/java/org/jfrog/build/client/ArtifactoryVersion.java
build-info-client/src/main/java/org/jfrog/build/client/Version.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/client/VersionTest.java

-----
Related to: https://github.com/jfrog/jenkins-artifactory-plugin/pull/282

Make 'Version' super class of 'ArtifactoryVersion'

---

build.gradle

Upgrade commons-io dependency to latest

---

README.md
build-info-api/src/main/java/org/jfrog/build/api/Build.java
build-info-api/src/main/java/org/jfrog/build/api/builder/BuildInfoBuilder.java
build-info-api/src/test/java/org/jfrog/build/api/builder/BuildInfoBuilderTest.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBuildInfoClient.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/issuesCollection/IssuesCollector.java

[Related PR](https://github.com/jfrog/jenkins-artifactory-plugin/pull/301)

Remove deprecated vcsRevision & vcsUrl properties json schema

---

Distribute.Jenkinsfile

DEVF-870 - Added credentials

---

Jenkinsfile

Changed jdk and credentials

---

README.md
appveyor.yml

Update testing instructions in README.md, Change testing execution in appveyor.yml

---

build-info-api/src/test/java/org/jfrog/build/api/BuildTest.java
build-info-api/src/test/java/org/jfrog/build/api/builder/BuildInfoMavenBuilderTest.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/issuesCollection/IssuesCollector.java

Fixes https://www.jfrog.com/jira/browse/HAP-1334
[Related PR](https://github.com/jfrog/jenkins-artifactory-plugin/pull/302)

HAP-1334 - BugFix collecting issues from different git repositories

---

Jenkinsfile

DEVF-898 - Changed jdk tool name

---

build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClientBuilder.java
build.gradle

-----
* Allow configuring the user agent to allow setting it in the IDE plugins.
* Allow configuring the SSL context to allow using Intellij's and Eclipse trust store.
* Update dependencies.

BI-531 - PreemptiveHttpClient improvements for the IDEs

---

build-info-api/src/main/java/org/jfrog/build/api/Build.java

Issues.collect failing for missing 'type' property

---

build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoVersionUtils.java
build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoZipBallStreamer.java

Go extractor - Add Support for packing nested go modules

---

build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/DockerUtils.java
build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/extractor/DockerPull.java
build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/extractor/DockerPush.java

-----
Fixes https://github.com/jfrog/jenkins-artifactory-plugin/issues/268#issuecomment-678318546

Set custom java temp dir for docker java.

---

Jenkinsfile

Update Jenkins file

---

build.gradle

BI-535 - Remove SLF4J Warning messages from the console log in npm, docker and pip builds

---

build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/DotnetDriver.java
build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/ToolchainDriverBase.java
build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/extractor/NugetRun.java

HAP-1395 - NuGet/DotNet is omitting the port in Artifactory URL

---

build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/extractor/NugetRun.java

BI-538 - Schema changes for aggregated builds - Fix NuGet

---

build-info-extractor-pip/src/test/java/org/jfrog/build/extractor/pip/extractor/PipExtractorTest.java

Fix pip extractor test

---

Jenkinsfile

-----
In order to allow automatic SCM build trigger, we should allow to run this job without specifying parameters.
When no projects are selected - build all projects.

Build automation - build all if none selected

---

build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/NpmDriver.java
build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmBuildInfoExtractor.java
build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmCommand.java
build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmInstallCi.java
build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/types/NpmProject.java
build-info-extractor-npm/src/test/java/org/jfrog/build/extractor/npm/extractor/NpmExtractorTest.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientConfigurationFields.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientProperties.java

Add npm ci support

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBaseClient.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBuildInfoClient.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/DependenciesDownloaderHelper.java

Move checksum consts to ArtifactoryBaseClient

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/GitUtils.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/util/GitUtilsTest.java
build-info-extractor/src/test/resources/gitutils/git_submodule_.git_suffix
build-info-extractor/src/test/resources/gitutils/git_submodule_parent_.git_suffix/HEAD
build-info-extractor/src/test/resources/gitutils/git_submodule_parent_.git_suffix/config
build-info-extractor/src/test/resources/gitutils/git_submodule_parent_.git_suffix/modules/subDir/subModule/HEAD
build-info-extractor/src/test/resources/gitutils/git_submodule_parent_.git_suffix/modules/subDir/subModule/config
build-info-extractor/src/test/resources/gitutils/git_submodule_parent_.git_suffix/modules/subDir/subModule/refs/heads/submodule

BI-541 - Support VCS details collection from git submodule

---

build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClient.java
build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClientBuilder.java
build-info-client/src/test/java/org/jfrog/build/client/PreemptiveHttpClientBuilderTest.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBuildInfoClient.java

Following [jenkins-artifactory-plugin#366](https://github.com/jfrog/jenkins-artifactory-plugin/issues/366).

BI-549 - PreemptiveHttpClient is missing credentials when initialized with proxy

---

build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmBuildInfoExtractor.java

-----
Resolves https://github.com/jfrog/jenkins-artifactory-plugin/issues/396

BI-555 - Npm install falls with a NullPointerException

---

Jenkinsfile

-----
* Fix issue when selecting 'ALL' and 'Release Staging':
> java.lang.NullPointerException: Cannot get property 'releaseVersion' on null object
* Change email to eco-system@jfrog.com

Improve release script

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/buildScanTable/BuildScanTableHelper.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/Severity.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/scan/SeverityTest.java

Fix typo: FromString -> fromString

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/buildScanTable/BuildScanTableHelper.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/buildScanTable/BuildScanTableHelperTest.java

Fix for bug where broken data causes NullPointerException

---

build-info-api/src/main/java/org/jfrog/build/api/Dependency.java
build-info-api/src/main/java/org/jfrog/build/api/builder/DependencyBuilder.java
build-info-api/src/test/java/org/jfrog/build/api/DependencyTest.java
build-info-api/src/test/java/org/jfrog/build/api/builder/DependencyBuilderTest.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildInfoExtractorUtilsTest.java

-----
Change the requiredBy field from `List<String>` to `String[][]`.

BI-558 - Improve requiredBy field to support path to root

---

build-info-api/src/main/java/org/jfrog/build/api/Vcs.java
build-info-api/src/test/java/org/jfrog/build/api/BuildTest.java

BI-560 - Add branch to Vcs

---

build-info-api/src/main/java/org/jfrog/build/api/Dependency.java
build-info-api/src/main/java/org/jfrog/build/api/builder/DependencyBuilder.java
build-info-api/src/test/java/org/jfrog/build/api/DependencyTest.java
build-info-api/src/test/java/org/jfrog/build/api/builder/DependencyBuilderTest.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildInfoExtractorUtilsTest.java

-----
Rename requiredBy to requestedBy.

BI-559 - Rename requiredBy to requestedBy

---

Jenkinsfile

-----
Make sure build-info built first.

Fix release script

---

build-info-api/src/main/java/org/jfrog/build/api/Vcs.java
build-info-api/src/test/java/org/jfrog/build/api/BuildTest.java

BI-564 - Add commit message to VCS

---

build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmExtractorConsumer.java

build-info-extractor-npm fix tests

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/DeploymentUrlUtils.java

-----
Related PR: https://github.com/jfrog/jenkins-artifactory-plugin/pull/436
Fixes:https://github.com/jfrog/jenkins-artifactory-plugin/issues/371

Bugfix - upload files with props omit multiple slashes

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/Severity.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/scan/SeverityTest.java

-----
Remove the deprecated "minor" and "major" severities and set "critical" as 1 level above "high".

BI-566 - Update severities in dependency tree

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBuildInfoClient.java

Add status code 202 validation to the usage report response

---

README.md

Update docker tests on README

---

build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ArtifactoryDependencyResolutionListener.groovy

-----
Following #475 , [jfrog/jfrog-cli/1055](https://github.com/jfrog/jfrog-cli/issues/1055)

Fix Gradle circular dependency resolution

---

build.gradle

Upgrade xstream to 1.4.16

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBuildInfoClient.java

Remove unused javadoc

---

build.gradle
ci/pipelines.release.yml

-----
* Sign artifacts only when `-Psign` flag is provided
* Alias `install` task to `publishToMavenLocal`

Release automation - minor changes

---

build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/DotnetDriver.java
build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/NugetDriver.java
build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/drivers/ToolchainDriverBase.java
build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/extractor/NugetRun.java
build-info-extractor-nuget/src/test/java/org/jfrog/build/extractor/nuget/extractor/NugetExtractorTest.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientConfigurationFields.java

-----
~ Change NuGet protocol from V2 to V3.
~ Improve dependencies source interpretation.

Nuget fixes

---

build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/extractor/NugetRun.java

Fix NuGet bug

---

build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/ArtifactoryPluginBase.groovy
build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleModuleExtractor.java
build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ArtifactoryDependencyResolutionListener.groovy
gradle.properties

Improve Gradle transitive dependency collection

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/ArtifactoryManager.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/SetProperties.java

-----
Better encapsulation of set properties service.

Refactoring set properties service

---

build-info-client/src/main/java/org/jfrog/build/client/ItemLastModified.java

-----
Fix: https://github.com/jfrog/jenkins-artifactory-plugin/issues/487

Bugfix - Artifactory Trigger cannot deserialize instance ItemLastModified

---

build.gradle

Update xstream to 1.4.17

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/ArtifactoryManager.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/ScanBuild.java

-----
Related PR: https://github.com/jfrog/jenkins-artifactory-plugin/pull/517

Add project to ScanBuild service

---

ci/pipelines.release.yml
ci/pipelines.snapshot.yml

Release automation - deploy to releases

---

build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/deploy/DeployableArtifactsUtils.java

Fix detailed summary target url for maven and gradle

---

build-info-extractor-docker/src/test/resources/org/jfrog/build/extractor/docker/maven-jib-example/pom.xml
build-info-extractor-gradle/src/test/resources/integration/gradle-example-ci-server/build.gradle
build-info-extractor-gradle/src/test/resources/integration/gradle-example-publish/build.gradle
build-info-extractor-gradle/src/test/resources/integration/gradle-example/build.gradle
build-info-extractor-gradle/src/test/resources/integration/gradle-kts-example-publish/build.gradle.kts

Change credentials ENV names from ARTIFACTORY to PLATFORM

---

build-info-client/src/main/java/org/jfrog/build/client/DeployableArtifactDetail.java
build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/ModuleParallelDeployHelper.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/deploy/DeployDetails.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/deploy/DeployableArtifactsUtils.java

Rollback artifactTarget and add targetRepo to json output

---

README.md

Minor Readme update

---

build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/GradlePluginTest.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/issuesCollection/IssuesCollectorTest.java

-----
* Remove unnecessary cleanup atciServerResolverOnlyTest 
* Move cleanup at IssuesCollectorTest to the end of the test

Fix IssuesCollectorTest

---

build-info-extractor-docker/src/test/java/org/jfrog/build/extractor/docker/extractor/DockerExtractorTest.java

dockerPushToVirtualTest should push to virtual repo

---

README.md
build-info-extractor-docker/src/test/java/org/jfrog/build/extractor/docker/extractor/DockerExtractorTest.java
build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/extractor/GoExtractorTest.java
build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/GradlePluginTest.java
build-info-extractor-npm/src/test/java/org/jfrog/build/extractor/npm/extractor/NpmExtractorTest.java
build-info-extractor-nuget/src/test/java/org/jfrog/build/extractor/nuget/extractor/NugetExtractorTest.java
build-info-extractor-pip/src/test/java/org/jfrog/build/extractor/pip/extractor/PipExtractorTest.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/AccessManager.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/CreateProject.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/DeleteProject.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/GetProject.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/UpdateProject.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/access/services/Utils.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/AccessManagerTest.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/DistributionManagerTest.java
build-info-extractor/src/test/resources/projectsConf/conf.json
build-info-extractor/src/testFixtures/java/org/jfrog/build/IntegrationTestsBase.java

Add Projects APIs

---

build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoCommand.java
build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoPublish.java
build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoRun.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientConfigurationFields.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientProperties.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/PublishBuildInfo.java

Run Go on new Java process

---

README.md
build-info-extractor-docker/src/test/java/org/jfrog/build/extractor/docker/extractor/DockerExtractorTest.java
build-info-extractor-docker/src/test/resources/org/jfrog/build/extractor/docker/maven-jib-example/pom.xml
build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/extractor/GoExtractorTest.java
build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/GradlePluginTest.java
build-info-extractor-gradle/src/test/resources/integration/gradle-example-ci-server/build.gradle
build-info-extractor-gradle/src/test/resources/integration/gradle-example-publish/build.gradle
build-info-extractor-gradle/src/test/resources/integration/gradle-example/build.gradle
build-info-extractor-gradle/src/test/resources/integration/gradle-kts-example-publish/build.gradle.kts
build-info-extractor-npm/src/test/java/org/jfrog/build/extractor/npm/extractor/NpmExtractorTest.java
build-info-extractor-nuget/src/test/java/org/jfrog/build/extractor/nuget/extractor/NugetExtractorTest.java
build-info-extractor-pip/src/test/java/org/jfrog/build/extractor/pip/extractor/PipExtractorTest.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/AccessManagerTest.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/DistributionManagerTest.java
build-info-extractor/src/testFixtures/java/org/jfrog/build/IntegrationTestsBase.java

Rename test env var to admin token

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/Issue.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/scan/DependencyTreeTest.java

Add CVE ID to issue

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/Artifact.java

-----
Following feedback here:
https://github.com/jfrog/ide-plugins-common/pull/61#discussion_r740869155

Improve construction of scan Artifact

---

build.gradle

-----
We should use the latest release of the Gradle Artifactory plugin.

Use the latest release of the Gradle plugin

---

build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientProperties.java

-----
Related: https://github.com/asafgabai/build-info-go/pull/1

Deprecate 'artifactory.' properties prefix

---

build-info-extractor-gradle/src/test/resources/integration/buildinfo.properties.deployer
build-info-extractor-gradle/src/test/resources/integration/buildinfo.properties.resolver
build-info-extractor/src/test/java/org/jfrog/build/extractor/client/DeploymentUrlUtilsTest.java

-----
Related: https://github.com/jfrog/build-info/commit/8e6da85721ea6c5a9fdeb338245ecbe022fe071e

Fix failing tests caused by removing 'artifactory.'

---

RELEASE.md
build-info-api/src/main/java/org/jfrog/build/api/Artifact.java
build-info-api/src/main/java/org/jfrog/build/api/BaseBuildFileBean.java
build-info-api/src/main/java/org/jfrog/build/api/Dependency.java
build-info-extractor-gradle/src/test/resources/integration/buildinfo.properties.deployer
build-info-extractor-gradle/src/test/resources/integration/buildinfo.properties.resolver
build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildDeploymentHelper.java
build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ClientProperties.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/DependenciesDownloaderHelper.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/client/DeploymentUrlUtilsTest.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/util/DownloadTest.java
build.gradle
gradle.properties

revert d4ae15a351bae4824f63c82fe3d56632c79631da..ae159369fec1f7c95be2bc9692c4b3e85e08f8d0

---

build-info-extractor-npm/src/test/java/org/jfrog/build/extractor/npm/extractor/NpmExtractorTest.java
build-info-extractor-npm/src/test/resources/integration/settings/build-info-tests-npm-remote.json
build-info-extractor-npm/src/test/resources/integration/settings/build-info-tests-npm-virtual.json
build-info-extractor-npm/src/test/resources/org/jfrog/build/extractor/a/package-lock.json
build-info-extractor-npm/src/test/resources/org/jfrog/build/extractor/b/package-lock.json
build-info-extractor-npm/src/test/resources/org/jfrog/build/extractor/c/package-lock.json

-----
* Avoid using remote and virtual repositories
* Add `package-lock.json` files.

Improve npm extractor tests

---

build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/GoDriverTest.java

-----
Precondition for:
* https://github.com/jfrog/ide-plugins-common/pull/65

Allow ignoring go list errors

---

release/pipelines.release.yml
release/pipelines.snapshot.yml
release/specs/dev-rbc-filespec.json

Fix release scripts

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/Artifact.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/ci/BuildInfo.java

Bugfix - NRE Check for module type

---

build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoZipBallStreamer.java

Bugfix - Fix isVendorPackage

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/scan/Issue.java

IDEs - compare scan issues by ID

---

build-info-client/src/main/java/org/jfrog/build/client/DeployableArtifactDetail.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/deploy/DeployableArtifactsUtils.java

Save late deploy artifacts properties

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/builder/ArtifactBuilder.java

-----
Resolves: https://github.com/jfrog/jenkins-artifactory-plugin/issues/610

Bugfix - Add 'localpath' to artifact builder

---

build-info-api/src/main/java/org/jfrog/build/api/util/FileChecksumCalculator.java
build.gradle

-----
Fixes https://github.com/jfrog/jenkins-artifactory-plugin/issues/624
Fixes https://github.com/jfrog/jenkins-artifactory-plugin/issues/621

Remove AmazonCorrettoCryptoProvider code

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/ArtifactoryManager.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/services/StageBuild.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryManagerTest.java

-----
Resolves https://github.com/jfrog/jenkins-artifactory-plugin/issues/627

Support build promotion with projects

---

build.gradle

Update xstream to 1.4.19

---

build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleArtifactoryClientConfigUpdater.java
build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/DeployTask.java
build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/ArtifactoryClientConfiguration.java

-----
Fixes: https://github.com/jfrog/jfrog-cli/issues/1462
Related: https://github.com/jfrog/jfrog-cli/pull/1467

Bugfix - Set properties to Maven artifacts

---

build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/Consts.java
build-info-extractor-gradle/src/test/java/org/jfrog/gradle/plugin/artifactory/GradlePluginTest.java

-----
* Add Gradle 7 tests
* Update Gradle 6 version

Update Gradle tests

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/RepositoryType.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/artifactory/ArtifactoryManager.java

-----
Dependency for https://github.com/jfrog/teamcity-artifactory-plugin/pull/129

Add getFederatedRepositoriesKeys to ArtifactoryManager

---

build.gradle

Downgrade slf4j to 1.7.36

---

build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/GoDriver.java
build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoDependencyTree.java

Fix javadoc

---

build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/extractor/GoDependencyTreeTest.java

Fix Go tests on Java 8

---

.github/workflows/integrationTests.yml

Run push tests only on the master branch

---

build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoPublish.java
build-info-extractor-go/src/test/java/org/jfrog/build/extractor/go/extractor/GoZipBallStreamerTest.java
build-info-extractor-nuget/src/main/java/org/jfrog/build/extractor/nuget/extractor/NugetRun.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/ModuleExtractorUtils.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/JsonSerializer.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/util/JsonUtils.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/usageReport/UsageReporter.java

Refactor and handle unhandled exceptions

---

README.md

Add Latest Tag badge

---

build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/ArtifactoryProjectBuilder.java

Reverts jfrog/build-info#683 due to these issues:
https://github.com/jfrog/jfrog-azure-devops-extension/issues/381
https://github.com/jfrog/jenkins-artifactory-plugin/issues/734
https://github.com/jfrog/jfrog-cli/issues/1839

Revert "Removed the dummy remote repository in favour for the snapshot and re…"

---

build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/GradleBuildInfoExtractor.java
build-info-extractor-ivy/src/main/java/org/jfrog/build/extractor/listener/ArtifactoryBuildListener.java
build-info-extractor-maven3/src/main/java/org/jfrog/build/extractor/maven/BuildInfoRecorder.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/packageManager/PackageManagerExtractor.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/packageManager/PackageManagerUtils.java

Refactor 'collectAndFilterEnvIfNeeded' func

---

.github/workflows/frogbot-scan-pr-gradle.yml

-----
Add pull requests scanning by [Frogbot](https://github.com/jfrog/frogbot#readme) to this repository.

Add PR scanning by Frogbot to this repository

---

.github/release.yml

Generate release notes using GitHub-Action

---

build-info-extractor-maven3/src/main/resources/META-INF/plexus/components.xml

-----
Fix https://github.com/jfrog/jfrog-cli/issues/1964

Fix NPE in Maven 3.9.2

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/executor/CommandExecutor.java

Add timeout for exeCommand utility

---

build-info-extractor/src/main/java/org/jfrog/build/extractor/usageReport/UsageReporter.java

Report Usage - Add SSL context

---

release/pipelines.release.yml

Improve release checks

---

build.gradle

-----
Fix https://github.com/jfrog/build-info/issues/756

Upgrade commons-compress to 1.24

---

build-info-extractor-pip/src/test/java/org/jfrog/build/extractor/pip/extractor/PipExtractorTest.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java
build-info-extractor/src/main/java/org/jfrog/build/extractor/packageManager/PackageManagerUtils.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/BuildExtractorUtilsTest.java
build-info-extractor/src/test/java/org/jfrog/build/extractor/packageManager/PackageManagerUtilsTest.java

Build info property key can only be obtained from environment variables

---

build-info-api/src/main/java/org/jfrog/build/api/builder/ModuleType.java

Add CPP module type

---

build.gradle

-----
Update Guava to include https://github.com/google/guava/commit/f87f68cd3e032a082a7702f3143862a9b27422fe that fixes https://github.com/google/guava/issues/6634.

Update Guava and commons-compress

---

build-info-extractor-npm/src/main/java/org/jfrog/build/extractor/npm/extractor/NpmPublish.java
build.gradle

Bump commons-compress to 1.26.2

---

.github/workflows/integrationTests.yml

-----
Update setup .NET action

Update setup .NET action

---

build-info-extractor-go/src/main/java/org/jfrog/build/extractor/go/extractor/GoZipBallStreamer.java

RTDEV-62881 - Modify Go pack zip LICENSE for submodules
